### ISSUE TITLE
Should we allow empty input list? 

### ISSUE THREAD

**Issue by juanmbellini** [coding-eval-platform/executor-service#24]
Related to coding-eval-platform/evaluations-service#38

**Comment by lobo** [comment]
I would not do it, for the time being... (what is easier for you?) 😆

**Comment by juanmbellini** [comment]
Its easier to not allow empty input lists, which is what we have now, but I think that is not correct.
Lets leave this for later

**Comment by lobo** [comment]
Ok, I'll always allow input lists anyway for now then.

**Comment by juanmbellini** [comment]
yes, admit

**Comment by juanmbellini** [comment]
Will be implemented in #32
