### ISSUE TITLE
In case the result is not a time out, it will always be an unknown error

### ISSUE THREAD

**Issue by juanmbellini** [coding-eval-platform/executor-service#30]
https://github.com/coding-eval-platform/executor-service/blob/60efa7798694453034b09cb48f5a8c6077d4b819/executor-service-application/executors/template.sh#L100

Should we handle this in another way? How?

**Comment by lobo** [comment]
@juanmbellini same way as the previous question asked: to be handled on a case by case basis (exam situation) or by refreshing the page (playground)

**Comment by juanmbellini** [comment]
This issue is related to how the executor work, nothng to do with exams and playground

**Comment by lobo** [comment]
ok, answered via audio message <3

**Comment by juanmbellini** [comment]
Note that syntax errors in ruby code will issue an unknown error. Also, if the code (java, ruby, c, or any language) executes an exit instruction with any other value than 0 (execution finishes) or 124 (timeout), an unknown error will be issued.

@lobo

**Comment by lobo** [comment]
lovely, no worries ❤️

**Comment by juanmbellini** [comment]
This is partially fixed by returning all execution results (stdout, stderr, exit code, etc). Is being fixed in #33 .
